service: crypto-scraper
frameworkVersion: '3'

custom:
  tableName: 'cs-tokensTable-${opt:stage}'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: "${env:region, 'us-west-2'}"
  environment:
    TOKENS_TABLE_NAME: '${self:custom.tableName}'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: { "Fn::GetAtt": ["TokensDynamoDbTable", "Arn"] }

functions:
  post_tokens:
    name: 'cs-post-tokens-${opt:stage}'
    handler: src/api/tokens.postTokens
    events:
      - http:
          path: /tokens
          method: POST
  get_tokens:
    name: 'cs-get-tokens-${opt:stage}'
    handler: src/api/tokens.getTokens
    events:
      - http:
          path: /tokens
          method: GET
  delete_token:
    name: 'cs-delete-token-${opt:stage}'
    handler: src/api/tokens.deleteToken
    events:
      - http:
          path: /tokens/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true
  get_token:
    name: 'cs-get-token-${opt:stage}'
    handler: src/api/tokens.getToken
    events:
      - http:
          path: /tokens/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    TokensDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: tokenId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: tokenId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:custom.tableName}
